Repository 2024-yju-capston-team3/project_fukuoka-album-deployment-repo, pull requests merged in 2023-11, with the labels that each got.

#80 refact: modify post editFunction
  src/components/write/index.tsx
  src/components/write/writeStyles.ts
  src/services/write.service.ts
Labels: 🔨 Refactor

#81 💄 style: Add team page route and menu item
  src/Router.tsx
  src/components/layout/header/index.tsx
  src/pages/teampage/index.tsx
Labels: 🎨 Html&css

#82 feat: Implememt Auth modal
  package.json
  src/components/layout/header/HeaderStyles.ts
  src/components/layout/header/index.tsx
  src/components/modal/auth/ModalStyles.ts
  src/components/modal/auth/index.tsx
  src/components/modal/auth/logIn/index.tsx
  src/components/modal/auth/register/index.tsx
  src/services/auth.service.ts
  src/services/signIn.service.ts
  src/types/auth.interface.ts
Labels: ⚙ Setting, 🔨 Refactor, ✨ Feature, 📬 API, 🎨 Html&css

#83 ✨ feat: Refactor team page component and update member card component
  src/components/memberCard/CardStyles.ts
  src/components/memberCard/index.tsx
  src/components/modal/member/index.tsx
  src/pages/teampage/index.tsx
  src/services/member.service.ts
  src/store/member.ts
  src/types/member.interface.ts
  src/types/modal.interface.ts
Labels: ✨ Feature, 🎨 Html&css
