Repository 2024-yju-capston-team3/project_fukuoka-album-deployment-repo, pull requests merged in 2023-12, with the labels that each got.

#85 feat(service): Implement member service
  src/pages/teampage/index.tsx
  src/services/member.service.ts
  src/types/member.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#86 refactor: Refactor updateMember
  src/components/modal/member/index.tsx
  src/pages/teampage/index.tsx
  src/services/member.service.ts
  src/types/member.interface.ts
Labels: 🔨 Refactor, ✨ Feature

#88 📦 chore: Remove @react-oauth/google dependency
  package-lock.json
Labels: ⚙ Setting

#87 ✨ feat: Fix typos and update member card component
  src/components/memberCard/index.tsx
  src/components/modal/addMember/index.tsx
  src/components/modal/member/index.tsx
  src/pages/teampage/index.tsx
  src/services/member.service.ts
Labels: ✨ Feature, 🎨 Html&css

#89 feat : add Intro page
  package-lock.json
  package.json
  src/Router.tsx
  src/components/intro/IntroStyles.ts
  src/components/intro/ShowUp.tsx
  src/components/intro/Video.tsx
  src/components/intro/index.tsx
  src/components/layout/header/index.tsx
  src/components/write/index.tsx
  src/pages/intropage/index.tsx
  src/services/intro.service.ts
  src/services/write.service.ts
  src/types/intro.interface.tsx
Labels: ✨ Feature

#90 style: Modify CardStyles
  src/components/card/CardStyles.ts
  src/components/memberCard/CardStyles.ts
Labels: 🎨 Html&css

#91 refactor: modify editPost
  src/components/modal/post/index.tsx
  src/components/post/index.tsx
  src/components/write/index.tsx
  src/services/write.service.ts
  src/types/post.interface.ts
Labels: 🔨 Refactor

#93 fix : solve the problem in likeChecked
  src/components/modal/post/index.tsx
  src/components/post/index.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#94 feat(auth.service): add default image URL for user registration
  src/components/mypage/MyPageStyles.ts
  src/services/auth.service.ts
Labels: ✨ Feature, 🎨 Html&css

#95 fix : modify user service PUT to PATCH
  src/services/user.service.ts
Labels: 🔨 Refactor, 🐞 BugFix

#96 feat: Add 'db' script for json-server
  package.json
  src/components/card/CardStyles.ts
  src/components/memberCard/CardStyles.ts
  src/components/post/index.tsx
  src/services/api.service.ts
  src/services/write.service.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#97 refact: modify writeModal
  src/components/write/index.tsx
Labels: 🔨 Refactor

#98 Fix : Not display image & find method Error
  src/components/write/index.tsx
  src/services/write.service.ts
Labels: 🔨 Refactor, 🐞 BugFix
