Repository 2024-yju-capston-team3/project_fukuoka-album-deployment-repo, pull requests merged in 2023-10, with the labels that each got.

#1 init: Setting react project
  .gitignore
  README.md
  db.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: ⚙ Setting

#2 feat: Implement Google maps component & marker
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/components/Map/Map.tsx
Labels: ✨ Feature, 🎨 Html&css

#3 refactor: Modify variable naming
  .env.example
Labels: 🔨 Refactor

#4 feat: Implement marker API
  db.json
  src/API.ts
  src/components/Map/Map.tsx
  src/types.ts
Labels: ✨ Feature, 📬 API

#6 docs: Update README.md
  README.md
Labels: 📃 Docs

#7 feat: header 추가
  public/index.html
  public/logo.svg
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Map/Map.tsx
Labels: 🎨 Html&css

#8 feat: Implement footer
  src/App.tsx
  src/Layout/Footer.tsx
Labels: 🎨 Html&css

#9 refactor: Add db.json
  .gitignore
Labels: 🔨 Refactor

#10 feat: 메뉴바 추가
  package-lock.json
  package.json
  public/index.html
  public/menu.svg
  src/App.tsx
  src/components/Header/Header.tsx
  src/fonts/font.css
Labels: 🎨 Html&css

#11 feat: Implement router
  src/App.tsx
  src/Router.tsx
Labels: ✨ Feature, 📬 API

#13 refactor: Modify css structure
  src/components/Card/CardStyles.ts
  src/components/Card/index.tsx
  src/components/Map/MapStyles.ts
  src/components/Map/index.tsx
  src/components/layout/body/BodyStyles.ts
  src/components/layout/body/index.css
  src/components/layout/body/index.tsx
  src/components/layout/footer/FooterStyles.ts
  src/components/layout/footer/index.tsx
  src/components/layout/header/HeaderStyles.ts
  src/components/layout/index.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#14 feat: Implement header routing logic
  src/components/layout/header/index.tsx
Labels: ✨ Feature

#15 refactor: Delete db.json
  db.json
Labels: 🔨 Refactor

#16 feat: 검색창 추가
  public/search.svg
  src/components/Profile/index.tsx
  src/components/layout/header/HeaderStyles.ts
  src/components/layout/header/index.tsx
  src/pages/index.tsx
Labels: 🎨 Html&css

#18 feat: Implement MyPage layout & logic
  package-lock.json
  package.json
  public/img/miku.jpeg
  src/App.tsx
  src/Router.tsx
  src/assets/image/miku.jpeg
  src/components/Card/CardStyles.ts
  src/components/Card/index.tsx
  src/components/modal/ModalStyles.ts
  src/components/modal/index.tsx
  src/components/mypage/MyPageStyles.ts
  src/components/mypage/index.tsx
  src/pages/mypage/index.tsx
  src/services/user.service.ts
  src/types/card.interface.ts
  src/types/modal.interface.ts
  src/types/user.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#19 Refactor naming
  src/components/card/CardStyles.ts
  src/components/card/index.tsx
  src/components/map/MapStyles.ts
  src/components/map/index.tsx
  src/components/profile/index.tsx
Labels: 🔨 Refactor

#21 refactor: Modify header search layout & error
  src/components/layout/footer/index.tsx
  src/components/layout/header/HeaderStyles.ts
  src/components/map/index.tsx
  src/components/mypage/index.tsx
  src/components/profile/index.tsx
  src/pages/index.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#22 feat : Implement create board feat
  .gitignore
  package-lock.json
  src/components/album/index.tsx
  src/components/map/index.tsx
  src/components/post/PostStyles.ts
  src/components/post/index.tsx
  src/types/location.interface.ts
  src/types/post.interface.ts
Labels: ✨ Feature

#23 Refactor album
  src/components/album/index.tsx
  src/types/post.interface.ts
Labels: 🔨 Refactor

#25 style: Modify css logic
  src/components/modal/ModalStyles.ts
  src/components/modal/index.tsx
  src/components/mypage/MyPageStyles.ts
Labels: 🎨 Html&css

#26 refactor: Extract fetch functionality to service
  src/components/album/index.tsx
  src/services/album.service.ts
Labels: 🔨 Refactor

#27 style: Modify css style
  src/components/layout/body/BodyStyles.ts
  src/components/layout/header/HeaderStyles.ts
  src/components/map/MapStyles.ts
  src/components/mypage/MyPageStyles.ts
Labels: 🎨 Html&css

#30 refactor menuStyle
  src/components/layout/header/HeaderStyles.ts
  src/components/map/MapStyles.ts
Labels: 🎨 Html&css

#31 refactor: Modify post method repository
  src/components/album/index.tsx
  src/components/mypage/index.tsx
  src/services/album.service.ts
  src/services/post.service.ts
  src/services/user.service.ts
Labels: 🔨 Refactor, 📬 API

#32 feat: Added Google login functionality to the header menu
  package.json
  src/App.tsx
  src/components/layout/header/HeaderStyles.ts
  src/components/layout/header/index.tsx
  src/services/signIn.service.ts
  src/store/index.ts
  src/store/token.ts
  src/store/user.ts
  src/types/user.interface.ts
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#34 refactor: Refactor mypage
  package-lock.json
  src/components/modal/index.tsx
  src/components/mypage/MyPageStyles.ts
Labels: 🔨 Refactor, 🎨 Html&css

#35 add write menu
  src/components/layout/header/index.tsx
Labels: 🎨 Html&css

#36 fix: Modify google maps rendering logic
  src/App.tsx
  src/components/map/index.tsx
Labels: 🐞 BugFix

#37 feat : add get user.name & image & style to modal
  src/components/album/index.tsx
  src/components/mypage/index.tsx
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
Labels: ✨ Feature

#38 feat: Implement loading text & fix: fix AlbumStyles
  src/components/album/AlbumStyles.ts
  src/components/album/index.tsx
  src/components/layout/header/index.tsx
  src/components/post/index.tsx
  src/components/post/modal/ModalStyles.ts
Labels: ✨ Feature, 🐞 BugFix

#39 fix : image issue with Icon resizing
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
Labels: 🐞 BugFix

#40 refactor: Modify marker logic
  src/components/post/index.tsx
  src/services/location.service.ts
  src/services/post.service.ts
Labels: 🔨 Refactor, 📬 API

#41 feat: Implement verify and signOut functions
  src/Router.tsx
  src/components/Card/index.tsx
  src/components/card/CardStyles.ts
  src/components/layout/header/index.tsx
  src/components/modal/index.tsx
  src/components/mypage/MyPageStyles.ts
  src/components/mypage/index.tsx
  src/services/auth.service.ts
  src/services/signIn.service.ts
  src/services/user.service.ts
  src/types/modal.interface.ts
  src/types/user.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 📬 API, 🎨 Html&css

#43 feat: add writepage
  src/Router.tsx
  src/components/layout/header/index.tsx
  src/components/post/modal/index.tsx
  src/components/write/index.tsx
  src/components/write/writeStyles.ts
  src/pages/write/index.tsx
Labels: 🎨 Html&css

#42 feat: Implement like & comment counter
  src/components/album/index.tsx
  src/components/mypage/index.tsx
  src/components/post/PostStyles.ts
  src/components/post/index.tsx
  src/types/post.interface.ts
Labels: ✨ Feature

#44 fix: Add zIndex to overlay
  src/components/modal/index.tsx
  src/components/mypage/index.tsx
  src/components/post/modal/index.tsx
  src/services/auth.service.ts
Labels: 🔨 Refactor, 🐞 BugFix

#45 feat : add comment modal component & style
  src/components/mypage/index.tsx
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
  src/services/comment.service.ts
  src/types/comment.interface.ts
  src/types/post.interface.ts
Labels: ✨ Feature

#47 refactor: Rename Card to card
  src/components/card/index.tsx
Labels: 🔨 Refactor

#49 feat: Implement searching logic
  src/components/album/index.tsx
  src/components/layout/header/index.tsx
  src/components/map/index.tsx
  src/components/mypage/index.tsx
  src/services/post.service.ts
  src/store/index.ts
  src/store/search.ts
  src/types/post.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#48 refactor: Add zIndex in modal
  src/components/modal/index.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#50 feat : add more view & rename Comment to Content
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
Labels: ✨ Feature

#51 feat: add address
  package-lock.json
  package.json
  public/cancel.svg
  src/components/layout/header/HeaderStyles.ts
  src/components/layout/header/index.tsx
  src/components/write/index.tsx
  src/components/write/slide/index.tsx
  src/components/write/writeStyles.ts
  src/services/write.service.ts
Labels: 🎨 Html&css

#52 feat : add like feature
  src/components/post/modal/index.tsx
  src/components/post/modal/likeChecked.svg
  src/services/post.service.ts
  src/types/post.interface.ts
Labels: ✨ Feature

#54 feat : Add comment write, rewrite, delete feature
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/comment.svg
  src/components/post/modal/index.tsx
  src/services/comment.service.ts
  src/types/comment.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#53 feat: Implement service for api server
  src/Router.tsx
  src/components/modal/index.tsx
  src/services/api.service.ts
  src/services/auth.service.ts
  src/services/user.service.ts
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#57 refactor : Get comment id when add or delete
  src/components/post/modal/index.tsx
  src/services/comment.service.ts
  src/types/post.interface.ts
Labels: 🔨 Refactor

#58 feat: Implement like & comment counter
  src/components/post/index.tsx
  src/components/post/modal/index.tsx
Labels: ✨ Feature

#59 refactor: Modify likeChecked icon
  src/components/post/PostStyles.ts
  src/components/post/index.tsx
  src/components/post/likeChecked.svg
  src/types/post.interface.ts
Labels: 🔨 Refactor

#60 feat: Implement Scrolling
  src/components/album/index.tsx
  src/components/post/index.tsx
Labels: ✨ Feature

#61 fix: Fix scrolling
  src/components/album/index.tsx
Labels: 🐞 BugFix

#63 fix: Fix fetchOptions function
  src/Router.tsx
  src/components/layout/header/index.tsx
  src/services/api.service.ts
  src/services/auth.service.ts
  src/services/user.service.ts
  tsconfig.json
Labels: ⚙ Setting, 📬 API

#62 feat: add image미리보기 & modal
  src/Router.tsx
  src/components/layout/header/index.tsx
  src/components/write/index.tsx
  src/components/write/slide/index.tsx
  src/pages/write/index.tsx
  src/services/write.service.ts
  src/store/index.ts
  src/store/modal.ts
  src/types/user.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#64 refactor: Delete unnecessary code
  src/Router.tsx
Labels: 🔨 Refactor

#65 feat : Add reply feature
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
  src/services/comment.service.ts
  src/types/comment.interface.ts
Labels: ✨ Feature, 🎨 Html&css

#66 Refactor: refactor api.services
  src/services/api.service.ts
  src/services/auth.service.ts
  src/services/signIn.service.ts
  tsconfig.json
Labels: ⚙ Setting, 🔨 Refactor, 📬 API

#67 feat : add modal image slide feature
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
  src/services/location.service.ts
Labels: ✨ Feature

#68 refact: modify uploadPostImage
  src/components/layout/header/index.tsx
  src/components/write/index.tsx
  src/components/write/writeStyles.ts
  src/services/api.service.ts
  src/services/write.service.ts
  src/types/post.interface.ts
Labels: 🔨 Refactor

#69 refactor(store): Remove tokenReducer from rootReducer
  src/components/layout/header/index.tsx
  src/services/api.service.ts
  src/services/auth.service.ts
  src/services/comment.service.ts
  src/services/location.service.ts
  src/services/post.service.ts
  src/services/user.service.ts
  src/store/index.ts
  src/store/token.ts
Labels: 🔨 Refactor, 📬 API

#70 refact: modify uploadPostImage
  src/components/post/modal/index.tsx
  src/components/write/index.tsx
  src/services/write.service.ts
Labels: 🔨 Refactor

#71 refactor : Post modal style change
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
  src/components/write/writeStyles.ts
  src/services/signIn.service.ts
  src/services/user.service.ts
Labels: 🔨 Refactor, 🐞 BugFix, 🎨 Html&css

#72 feat: add deleteButton
  public/post_menu.svg
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
  src/components/write/index.tsx
Labels: 🎨 Html&css

#74 feat: Add Post Delete
  src/components/post/modal/index.tsx
  src/services/post.service.ts
Labels: ✨ Feature

#73 fix(api): Fix error handling in uploadApi and add deleteImageApi
  src/components/modal/index.tsx
  src/services/api.service.ts
  src/services/user.service.ts
Labels: ✨ Feature, 📬 API

#75 refactor : Fix bug(reply comment) & code refactor
  src/components/post/modal/index.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#76 feat(api): add deleteTempImageFromDb function
  src/components/mypage/MyPageStyles.ts
  src/components/mypage/index.tsx
  src/components/write/index.tsx
  src/services/api.service.ts
  src/services/post.service.ts
  src/services/user.service.ts
  src/services/write.service.ts
Labels: ✨ Feature, 📬 API, 🐞 BugFix

#77 Writing page
  src/components/post/modal/ModalStyles.ts
  src/components/post/modal/index.tsx
  src/components/write/index.tsx
  src/services/post.service.ts
  src/services/write.service.ts
  src/types/post.interface.ts
Labels: 🔨 Refactor, ✨ Feature

#79 refactor : separate comment & reply feature
  src/components/modal/post/ModalStyles.ts
  src/components/modal/post/comment/index.tsx
  src/components/modal/post/index.tsx
  src/components/modal/post/like.svg
  src/components/modal/post/likeChecked.svg
  src/components/modal/post/reply/index.tsx
  src/components/post/index.tsx
  src/components/write/index.tsx
Labels: 🔨 Refactor
